# Generated by Django 5.2.3 on 2025-07-24 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rspv',
            field=models.ManyToManyField(blank=True, related_name='rspv_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participants', to='event.event'),
        ),
    ]
