# Generated by Django 5.2.3 on 2026-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_rpsv',
            field=models.BooleanField(default=False),
        ),
    ]
