# Generated by Codex on 2026-05-12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_is_rpsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
