# Generated by Django 5.2.3 on 2025-07-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='event_asset'),
        ),
    ]
