# Generated by Django 5.2.3 on 2025-07-10 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rpsv',
            field=models.ManyToManyField(blank=True, related_name='rspv_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
