# Generated by Django 5.2.3 on 2025-07-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_rpsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rpsv',
            new_name='rspv',
        ),
    ]
